# Generated by Django 4.2.7 on 2026-05-31 07:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(
                        choices=[
                            ("pattern_discovery", "Pattern Discovery Agent"),
                            ("predictor", "Predictive Analytics Agent"),
                            ("weak_area", "Weak Area Identification Agent"),
                            ("recommender", "Recommendation Engine Agent"),
                            ("supervisor", "Supervisor Agent"),
                        ],
                        help_text="Which agent ran this analysis",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current status of analysis",
                        max_length=20,
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(help_text="Input data provided to agent"),
                ),
                (
                    "output_data",
                    models.JSONField(
                        blank=True, help_text="Output produced by agent", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if execution failed",
                        null=True,
                    ),
                ),
                (
                    "execution_time_seconds",
                    models.FloatField(
                        blank=True, help_text="How long agent took to run", null=True
                    ),
                ),
                (
                    "tokens_used",
                    models.IntegerField(
                        blank=True,
                        help_text="LLM tokens used (for cost tracking)",
                        null=True,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When agent finished execution", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Analysis Log",
                "verbose_name_plural": "Analysis Logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User Question"),
                            ("assistant", "AI Response"),
                            ("system", "System Message"),
                        ],
                        help_text="Who sent this message",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="Message text")),
                (
                    "context_data",
                    models.JSONField(
                        blank=True,
                        help_text="Reference data used to answer (marks, predictions, etc.)",
                        null=True,
                    ),
                ),
                (
                    "sources",
                    models.JSONField(
                        default=list, help_text="Sources used for this response"
                    ),
                ),
                (
                    "is_helpful",
                    models.BooleanField(
                        blank=True,
                        help_text="User feedback on response quality",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Marks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marks_obtained",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Marks obtained by student",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_marks",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total marks for the exam",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="Percentage (auto-calculated)",
                        max_digits=5,
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("quiz", "Quiz"),
                            ("midterm", "Midterm"),
                            ("final", "Final Exam"),
                            ("assignment", "Assignment"),
                            ("practical", "Practical"),
                            ("project", "Project"),
                        ],
                        default="quiz",
                        help_text="Type of assessment",
                        max_length=20,
                    ),
                ),
                (
                    "exam_date",
                    models.DateField(help_text="Date when exam was conducted"),
                ),
                (
                    "topic",
                    models.CharField(
                        blank=True,
                        help_text="Specific topic/chapter for this exam",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Teacher comments or notes", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mark Entry",
                "verbose_name_plural": "Mark Entries",
                "ordering": ["-exam_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "predicted_marks",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Predicted percentage for next exam",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "predicted_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Predicted actual score (if max_marks known)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.85,
                        help_text="Model confidence (0-1, where 1 is 100% confident)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "lower_bound",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Lower confidence interval bound",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "upper_bound",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Upper confidence interval bound",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "prediction_for_date",
                    models.DateField(help_text="Date for which prediction is made"),
                ),
                (
                    "prediction_reason",
                    models.CharField(
                        choices=[
                            ("semester", "Semester Prediction"),
                            ("next_exam", "Next Exam Prediction"),
                            ("annual", "Annual Prediction"),
                            ("custom", "Custom Prediction"),
                        ],
                        default="next_exam",
                        help_text="Type of prediction",
                        max_length=50,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="XGBoost",
                        help_text="Which ML model made this prediction",
                        max_length=100,
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        default="1.0", help_text="Version of the model", max_length=20
                    ),
                ),
                (
                    "features_used",
                    models.JSONField(
                        blank=True, help_text="Features used for prediction", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prediction",
                "verbose_name_plural": "Predictions",
                "ordering": ["-prediction_for_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of recommendation", max_length=300
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of recommendation"
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("video", "Video Tutorial"),
                            ("article", "Article/Blog"),
                            ("practice", "Practice Problems"),
                            ("book", "Book Chapter"),
                            ("interactive", "Interactive Tool"),
                            ("quiz", "Practice Quiz"),
                            ("podcast", "Podcast"),
                        ],
                        default="practice",
                        help_text="Type of study resource",
                        max_length=50,
                    ),
                ),
                (
                    "topics_to_study",
                    models.JSONField(
                        default=list,
                        help_text="List of topics to focus on: ['Topic 1', 'Topic 2']",
                    ),
                ),
                (
                    "study_hours_suggested",
                    models.IntegerField(
                        default=5,
                        help_text="Suggested hours per week",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "study_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("3x_per_week", "3 times per week"),
                            ("2x_per_week", "2 times per week"),
                            ("weekly", "Weekly"),
                        ],
                        default="3x_per_week",
                        help_text="How often to study this",
                        max_length=50,
                    ),
                ),
                (
                    "resources",
                    models.JSONField(
                        default=list,
                        help_text="\n        List of resources: \n        [\n            {\n                'title': 'Khan Academy: Linear Equations',\n                'type': 'video',\n                'url': 'https://...',\n                'difficulty': 'beginner'\n            }\n        ]\n        ",
                    ),
                ),
                (
                    "generated_by_agent",
                    models.CharField(
                        default="RecommendationEngine",
                        help_text="Which AI agent generated this",
                        max_length=100,
                    ),
                ),
                (
                    "rag_query",
                    models.TextField(
                        blank=True,
                        help_text="RAG query used to retrieve resources",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this recommendation is currently active",
                    ),
                ),
                (
                    "completion_percentage",
                    models.IntegerField(
                        default=0,
                        help_text="How much of recommendation student has completed",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Recommendation",
                "verbose_name_plural": "Recommendations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the student", max_length=100
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Student email address (must be unique)",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "roll_number",
                    models.CharField(
                        blank=True,
                        help_text="Student roll number or ID",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Contact number", max_length=15, null=True
                    ),
                ),
                (
                    "grade_level",
                    models.IntegerField(
                        help_text="Grade/Class level (1-12)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "school",
                    models.CharField(
                        blank=True,
                        help_text="School/Institution name",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        help_text="Student profile picture",
                        null=True,
                        upload_to="student_profiles/",
                    ),
                ),
                (
                    "learning_style",
                    models.CharField(
                        choices=[
                            ("visual", "Visual Learner"),
                            ("auditory", "Auditory Learner"),
                            ("kinesthetic", "Kinesthetic Learner"),
                            ("reading_writing", "Reading/Writing Learner"),
                            ("mixed", "Mixed Learning Style"),
                        ],
                        default="mixed",
                        help_text="Preferred learning style",
                        max_length=50,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When student was added to system"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When student info was last updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Subject name (e.g., Mathematics, Physics)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Subject code (e.g., MATH101)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the subject", null=True
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon name for UI display",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#0ea5e9",
                        help_text="Hex color code for visualizations",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WeakArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Current average percentage in this subject",
                        max_digits=5,
                    ),
                ),
                (
                    "class_average",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Class average for comparison",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "gap_from_target",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="How many points below target performance",
                        max_digits=5,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical - Below 40%"),
                            ("severe", "Severe - 40-50%"),
                            ("moderate", "Moderate - 50-60%"),
                            ("mild", "Mild - 60-70%"),
                            ("warning", "Warning - Close attention needed"),
                        ],
                        default="moderate",
                        help_text="How critical this weak area is",
                        max_length=20,
                    ),
                ),
                (
                    "priority_rank",
                    models.IntegerField(
                        default=0,
                        help_text="Ranking among student's weak areas (lower = higher priority)",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Why this area is weak (from AI analysis)",
                        null=True,
                    ),
                ),
                (
                    "improvement_potential",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        help_text="Estimated percentage improvement possible",
                        max_digits=5,
                    ),
                ),
                ("identified_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student with weak area",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weakarea_set",
                        to="students.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="Subject identified as weak",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weakareas",
                        to="students.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weak Area",
                "verbose_name_plural": "Weak Areas",
                "ordering": ["priority_rank", "-identified_at"],
            },
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["email"], name="students_st_email_e271bc_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["roll_number"], name="students_st_roll_nu_6ff92b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["grade_level"], name="students_st_grade_l_30e3b9_idx"
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="student",
            field=models.ForeignKey(
                help_text="Student receiving recommendation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="subject",
            field=models.ForeignKey(
                help_text="Subject for this recommendation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to="students.subject",
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="weak_area",
            field=models.ForeignKey(
                blank=True,
                help_text="Related weak area (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recommendations",
                to="students.weakarea",
            ),
        ),
        migrations.AddField(
            model_name="prediction",
            name="student",
            field=models.ForeignKey(
                help_text="Student for whom prediction is made",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="predictions",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="prediction",
            name="subject",
            field=models.ForeignKey(
                help_text="Subject being predicted",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="predictions",
                to="students.subject",
            ),
        ),
        migrations.AddField(
            model_name="marks",
            name="student",
            field=models.ForeignKey(
                help_text="Student who took the exam",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marks_set",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="marks",
            name="subject",
            field=models.ForeignKey(
                help_text="Subject of the exam",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marks",
                to="students.subject",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="student",
            field=models.ForeignKey(
                help_text="Student in conversation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="analysislog",
            name="student",
            field=models.ForeignKey(
                help_text="Student being analyzed",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_logs",
                to="students.student",
            ),
        ),
        migrations.AddIndex(
            model_name="weakarea",
            index=models.Index(
                fields=["student", "subject"], name="students_we_student_5bc375_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weakarea",
            index=models.Index(
                fields=["severity"], name="students_we_severit_ef1ce6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="weakarea",
            unique_together={("student", "subject")},
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["student", "subject"], name="students_re_student_adb6e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["is_active"], name="students_re_is_acti_6eb6e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prediction",
            index=models.Index(
                fields=["student", "subject"], name="students_pr_student_eb422b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prediction",
            index=models.Index(
                fields=["prediction_for_date"], name="students_pr_predict_47f13b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marks",
            index=models.Index(
                fields=["student", "subject"], name="students_ma_student_684b4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marks",
            index=models.Index(
                fields=["exam_date"], name="students_ma_exam_da_bc99fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marks",
            index=models.Index(
                fields=["exam_type"], name="students_ma_exam_ty_84d26f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="marks",
            unique_together={("student", "subject", "exam_type", "exam_date")},
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["student", "created_at"], name="students_ch_student_8d0bb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysislog",
            index=models.Index(
                fields=["student", "agent_name"], name="students_an_student_cee1d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysislog",
            index=models.Index(fields=["status"], name="students_an_status_c10dba_idx"),
        ),
    ]
